language: python
python:
  - "3.5.3"
  - "3.6"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.7-dev"
    - python: "nightly"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - flake8 pysonos
  - pylint pysonos
  - py.test --cov-config .coveragerc --cov pysonos .

after_script:
  - coveralls

sudo: false
