language: python
python:
  - "3.5.3"
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - flake8 pysonos
  - pylint pysonos
  - py.test --cov-config .coveragerc --cov pysonos .

after_script:
  - coveralls

sudo: false
